# Generated by Django 4.1 on 2022-08-27 08:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nick',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='nick',
            name='title',
            field=models.CharField(max_length=17, verbose_name='Server '),
        ),
    ]
