# Generated by Django 4.1 on 2022-09-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nick', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nick',
            options={'ordering': ['-created_date']},
        ),
    ]
